### ISSUE TITLE
Roadmap for Fling

### ISSUE THREAD

**Issue by kxzxvbk** [kxzxvbk/Fling#19]
### Algorithms:

- [ ] FedAMP — [Personalized Cross-Silo Federated Learning on non-IID Data](https://ojs.aaai.org/index.php/AAAI/article/view/16960) AAAI 2021
 #25 
- [ ] FedPHP — [FedPHP: Federated Personalization with Inherited Private Models](https://link.springer.com/chapter/10.1007/978-3-030-86486-6_36) ECML PKDD 2021
- [ ] APPLE — [Adapt to Adaptation: Learning Personalization for Cross-Silo Federated Learning](https://www.ijcai.org/proceedings/2022/301) IJCAI 2022
- [ ] FedALA — [FedALA: Adaptive Local Aggregation for Personalized Federated Learning](https://ojs.aaai.org/index.php/AAAI/article/view/26330) AAAI 2023
- [ ] FedRep — [Exploiting Shared Representations for Personalized Federated Learning](http://proceedings.mlr.press/v139/collins21a.html) ICML 2021
- [ ] FedBABU — [Fedbabu: Towards enhanced representation for federated image classification](https://openreview.net/forum?id=HuaYQfggn5u) ICLR 2022
- [ ] FedGC — [Federated Learning for Face Recognition with Gradient Correction](https://ojs.aaai.org/index.php/AAAI/article/view/20095/19854) AAAI 2022
- [ ] FedCP — [FedCP: Separating Feature Information for Personalized Federated Learning via Conditional Policy](https://dl.acm.org/doi/10.1145/3580305.3599345) KDD 2023
- [ ] GPFL — [GPFL: Simultaneously Learning Generic and Personalized Feature Information for Personalized Federated Learning](https://arxiv.org/pdf/2308.10279v3.pdf) ICCV 2023
- [x] MOON — [Model Contrastive Federated Learning](https://openaccess.thecvf.com/content/CVPR2021/papers/Li_Model-Contrastive_Federated_Learning_CVPR_2021_paper.pdf) CVPR 2021 #26 

### Scenario

- [x] Cross domain. #36 

### System Design

- [ ] Publish python package.
- [ ] CI/CD + test pipeline.
- [x] Enhanced documents. #52 
- [x]  Chense doc: #23 

### Visualization Tools

- [x] Single loss-landscape visualizer and hessian eigen value analysis. #37 
- [x] Activation maximization method. #42

### Dataset
- [x] Mini-ImageNet. #27 
- [x] ImageNet. #28 #30 
- [x] AG-NEWS dataset (NLP classification task) #31
